site_name: Tabletop Simulator Knowledge&nbsp;Base
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/TSIcon.png'
  favicon: 'img/Icon-Dice.png'
  custom_dir: 'theme'

extra_css:
  - css/theme.css
  - css/table.css
  - css/type_icons.css
  - css/i_icons.css
  - css/player_color_table.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "\u0020"

repo_name: 'GitHub Source'
repo_url: 'https://github.com/Berserk-Games/Tabletop-Simulator-Knowledge-Base'

extra:
  social:
    - type: 'reddit'
      link: 'https://www.reddit.com/r/tabletopsimulator/'
    - type: 'twitter'
      link: 'https://twitter.com/tabletopsim'
    - type: 'facebook'
      link: 'https://www.facebook.com/tabletopsimulator'
    - type: 'youtube'
      link: 'https://www.youtube.com/user/berserkgames'


nav:
  - Getting Started:
    - Tabletop Simulator: index.md
    - Technical Info: getting-started/technical-info.md
    - Launch Options: getting-started/launch-options.md
    - Configuration Menu: getting-started/configuration-menu.md
    - Help Menu: getting-started/help-menu.md
    - In-Game Communication: getting-started/in-game-communication.md
    - Chat Rules: getting-started/chat-rules.md
    - Player Roles: getting-started/player-roles.md
    - Video Tutorials: getting-started/video-tutorials.md
    - Games - Classic: getting-started/games-classic.md
    - Games - DLC: getting-started/games-dlc.md
    - Games - Workshop: getting-started/games-workshop.md
    - Games - Save & Load: getting-started/games-save-load.md
    - FAQ: getting-started/faq.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Game Tools:
    - Drawing Tool: game-tools/drawing-tools.md
    - Zone Tools: game-tools/zone-tools.md
    - Line Tool: game-tools/line-tool.md
    - Flick Tool: game-tools/flick-tool.md
    - Joint Tool: game-tools/joint-tool.md
    - Text Tool: game-tools/text-tool.md
    - Gizmo Tool: game-tools/gizmo-tool.md
    - Snap Point Tool: game-tools/snap-point-tool.md
    - Decal Tool: game-tools/decal-tool.md
  - Player Guides:
    - Controls & Movement: player-guides/basic-controls.md
    - Advanced Controls: player-guides/advanced-controls.md
    - BB Codes: player-guides/bb-codes.md
    - Blindfold: player-guides/blindfold.md
    - Block List: player-guides/block-list.md
    - Camera Control: player-guides/camera-states.md
    - Changing Color: player-guides/changing-color.md
    - Context Menu: player-guides/context-menu.md
    - Notebook: player-guides/notebook.md
    - Notes (on-screen): player-guides/notes.md
    - Teams: player-guides/teams.md
  - Host Guides:
    - Creating States: host-guides/creating-states.md
    - Custom Background: host-guides/custom-background.md
    - Lighting: host-guides/lighting.md
    - Permissions: host-guides/permissions.md
    - Player Hands: host-guides/player-hands.md
    - Physics: host-guides/physics.md
    - Grids: host-guides/grids.md
    - Turns: host-guides/turns.md
    - Spawning Objects: host-guides/spawning-objects.md
    - Tables: host-guides/tables.md
  - Custom Content:
    - About Custom Objects: custom-content/about-custom-objects.md
    - Asset Creation: custom-content/asset-creation.md
    - Asset Importing: custom-content/asset-importing.md
    - Cloud Manager: custom-content/cloud-manager.md
    - Custom AssetBundle: custom-content/custom-assetbundle.md
    - Custom Board: custom-content/custom-board.md
    - Custom Deck: custom-content/custom-deck.md
    - Custom Dice: custom-content/custom-dice.md
    - Custom Figurine: custom-content/custom-figurine.md
    - Custom Jigsaw: custom-content/custom-jigsaw.md
    - Custom Model: custom-content/custom-model.md
    - Custom Tile: custom-content/custom-tile.md
    - Custom Token: custom-content/custom-token.md
    - Steam Workshop: custom-content/steam-workshop.md
    - Importing Mods: custom-content/importing-mods.md
    - Save File Format: custom-content/save-file-format.md
    - Community Guides: custom-content/community-guides.md
